stages:
- name: Build
  steps:
  - runScriptConfig:
      image: node:alpine
      shellScript: |-
        mkdir -p /node/src/github.com/rancher
        ln -s `pwd` /node/src/github.com/rancher/pipeline-example-node
        cd /node/src/github.com/rancher/pipeline-example-node
        npm i
        npm start
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: node-server:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml